# Want to change this? Unleash the horrors within...
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
SCREEN_SIZE = [SCREEN_WIDTH, SCREEN_HEIGHT]

NUM_INJECTORS = 10

# How big can you take?
INJECTOR_SIZE = (SCREEN_WIDTH / 4, SCREEN_HEIGHT / (NUM_INJECTORS / 2))

# KETAMINE_COUNTER_SIZE = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 10)
BLACK = (0, 0, 0)
KETAMINE_COUNTER_COLOR = BLACK
UPGRADE_BUTTON_TEXT_COLOR = BLACK

FPS = 120  # Go big or go home
